#!/usr/bin/bash

cd ../public

rm todos.md # Clear todo file to avoid double counting to grep.

grep \#todo *.md > output.txt  # grabs #todo lines with grep

sed -i 's/.*.md/\r\[\[&\]\]\r/' output.txt  # replaces .*.md with \n [[.*.md]] \n
cat output.txt
sed -i 's/.md\]\]/\]\]/' output.txt # replaces .md]] with ]]
cat output.txt

# mv renames the file public-output.txt
mv output.txt ../public-output.txt

exit